version: '3.8'

services:
  csvserver_compose:
    image: infracloudio/csvserver
    ports:
      - "9399:9300"  # Exposes port 9393 on the host to port 9393 on the container
    volumes:
      - /home/ubunto/docker-compose/docker-compose-v:/docker-compose-v  # Mount a local directory (./data) to /data in the container
      - /home/ubunto/docker-compose/csvserver/inputdata:/csvserver/inputdata
      - /home/ubunto/docker-compose/csvserver/inputFile:/csvserver/inputFile
      - /home/ubunto/docker-compose/gencsv.sh:/csvserver/gencsv.sh
    environment:
      - CSV_FILE_PATH=/home/ubunto/docker-compose/csvserver/inputFile  # Adjust path based on your CSV file location
      - CSV_SERVER_HOST=0.0.0.0
      - CSV_SERVER_POST=9399
      - CSVSERVER_BORDER=Orange
    env_file:
      - .env
    restart: always

  prometheus_compose:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - /home/ubunto/docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

